enum SERVICE_TYPE {
  MODULE = "MODULE",
  API = "API",
  FRAGMENT = "FRAGMENT",
  INJECTABLE = "INJECTABLE",
  DATA_PROVIDER = "DATA_PROVIDER",
  RENDER_ENGINE = "RENDER_ENGINE"
}

enum META_TYPES {
  TYPE,
  CONFIGURATION,
  PATH,
  API_HANDLERS,
  FRAGMENT,
  HANDLER,
  FILE_PATH,
  RENDER_PARTIALS,
  ERROR_HANDLER
}

enum RENDER_TYPES {
  HANDLER,
  ERROR
}

enum ProcedureActionType {
  API = 'api',
  FRAGMENT = 'fragment'
}

const DEFAULT_RENDER_WORKER_COUNT = 1;

const API_PREFIX = '/api';

const DEVELOPMENT_PORT = 4444;

const DEFAULT_CONTENT_TIMEOUT = 2000;

export {
  ProcedureActionType,
  DEFAULT_CONTENT_TIMEOUT,
  RENDER_TYPES,
  DEVELOPMENT_PORT,
  DEFAULT_RENDER_WORKER_COUNT,
  API_PREFIX,
  SERVICE_TYPE,
  META_TYPES
}
