enum SERVICE_TYPE {
  MODULE = "MODULE",
  API = "API",
  FRAGMENT = "FRAGMENT",
  INJECTABLE = "INJECTABLE",
  DATA_PROVIDER = "DATA_PROVIDER",
  RENDER_ENGINE = "RENDER_ENGINE"
}

enum META_TYPES {
  TYPE,
  CONFIGURATION,
  PATH,
  API_HANDLERS,
  FRAGMENT,
  HANDLER,
  FILE_PATH
}

const DEFAULT_RENDER_WORKER_COUNT = 1;

const API_PREFIX = '/api';

const DEVELOPMENT_PORT = process.env.PORT ? +process.env.PORT : 4444;

export {
  DEVELOPMENT_PORT,
  DEFAULT_RENDER_WORKER_COUNT,
  API_PREFIX,
  SERVICE_TYPE,
  META_TYPES
}
